[workspace]
members = [
    "core", #   aareocams-core
    "scomm", #  aareocams-scomm
    "net", #    aareocams-net
    #"client", # aareocams-client
    #"server", # aareocams-server
    "dash", #   aareocams-dash
    "bot", #    aareocams-bot
]
resolver = "2"

[profile.speed]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
